---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: Remove Trailing Whitespaces
      - id: end-of-file-fixer
        name: Fix End-Of-File Endings
      - id: check-yaml
        name: Check YAML
      - id: check-added-large-files
        name: Check For Large Files
      - id: detect-private-key
        name: Detect Private Keys
      - id: check-merge-conflict
        name: Check For Merge Conflicts
      - id: mixed-line-ending
        name: Check Mixed Line Endings
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: YAML Lint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        name: Markdown Lint
        args:
          - "-c"
          - ".markdownlint.yaml"
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.4
    hooks:
      - name: Terraform FMT
        id: terraform_fmt
      - name: Terraform Validate
        id: terraform_validate
